### ISSUE TITLE
cert_create: strdup from string.h is defined as static function in src/main.c

### ISSUE THREAD

**Issue by bcran** [TrustedFirmware-A/trusted-firmware-a#10]
In tools/cert_create/src/main.c. a static function `strdup` is defined, but the same function is already declared non-static in string.h. This causes a build failure on FreeBSD.

**Comment by odeprez** [comment]
https://review.trustedfirmware.org/c/TF-A/trusted-firmware-a/+/30224

**Comment by ManishVB-Arm** [comment]
This patch is merged https://review.trustedfirmware.org/c/TF-A/trusted-firmware-a/+/30224. Please let me know your observation.

**Comment by odeprez** [comment]
Closing the ticket as the issue is hopefully resolved by Manish's change.
