### ISSUE TITLE
non-secure interrupt Interrupt response is slower when EHF is enabled

### ISSUE THREAD

**Issue by hyrtee** [TrustedFirmware-A/trusted-firmware-a#29]
A non secure interrupt comes when the cpu is running in optee's secure el1, if ATF turns on EHF, this non secure interrupt will be routed to EL3 for processing, but EL3 does not register the processing function for this interrupt, resulting in a delay in the interrupt processing. When the cpu returns from optee to the non secure world, the interrupt is responded to. How can we ensure that when a non secure interrupt occurs, it will be processed immediately in the non secure world while turning on EHF?

**Comment by odeprez** [comment]
Hi afaik enabling EHF together with OP-TEE isn't supported nor recommended.
