### ISSUE TITLE
fiptool: sys/mount.h include is unused

### ISSUE THREAD

**Issue by bcran** [TrustedFirmware-A/trusted-firmware-a#9]
It appears the include of sys/mount.h in tools/fiptool/fiptool.c is unused.
Including it causes a build failure on FreeBSD because the `u_` types aren't known.

**Comment by odeprez** [comment]
https://review.trustedfirmware.org/c/TF-A/trusted-firmware-a/+/30224

**Comment by ManishVB-Arm** [comment]
This patch is merged https://review.trustedfirmware.org/c/TF-A/trusted-firmware-a/+/30224. Please let me know your observation.
